"use strict";

/**
 * Supervision of the Python FastAPI backend.
 *
 * The desktop app is only usable when `quration.api.server` is reachable, so
 * the main process takes responsibility for it. Three behaviours matter:
 *
 *   1. If a backend is *already* healthy on the port we adopt it instead of
 *      spawning a rival that would die on EADDRINUSE. This is what makes
 *      `npm run dev:backend` in another terminal harmless.
 *   2. Startup failures surface the interpreter's own stderr. A bare
 *      "backend did not start" message hides the ImportError that explains it.
 *   3. Anything we spawned is torn down on quit, escalating to SIGKILL so a
 *      wedged uvicorn cannot outlive the window.
 */

const { spawn } = require("node:child_process");
const fs = require("node:fs");

const { resolvePythonPath } = require("./paths");

const DEFAULT_HOST = "127.0.0.1";
const DEFAULT_PORT = 8000;

/** Cold uvicorn startup pulls in heavy scientific imports; be patient. */
const DEFAULT_STARTUP_TIMEOUT_MS = 90_000;
const DEFAULT_POLL_INTERVAL_MS = 300;

/** Time a SIGTERM'd backend gets to exit before SIGKILL. */
const SHUTDOWN_GRACE_MS = 4_000;

/** How many log lines to retain for error reporting. */
const LOG_BUFFER_LINES = 200;

/**
 * Bounded FIFO of recent output lines.
 * @param {number} [limit]
 */
function createLogBuffer(limit = LOG_BUFFER_LINES) {
  const lines = [];
  return {
    push(chunk) {
      const incoming = String(chunk).split(/\r?\n/).filter((l) => l !== "");
      for (const line of incoming) {
        lines.push(line);
      }
      if (lines.length > limit) {
        lines.splice(0, lines.length - limit);
      }
    },
    tail(count = 25) {
      return lines.slice(-count).join("\n");
    },
    get length() {
      return lines.length;
    },
  };
}

/**
 * Path used to decide whether the server is up.
 *
 * Deliberately not `/health`: that route is a Kubernetes-style *readiness*
 * probe that Depends on an async Postgres session and a Redis client, so on a
 * machine without them it answers 500 forever and the app would never start.
 * `/openapi.json` is generated by FastAPI itself with no dependencies, so a
 * response proves the ASGI app is constructed and routing — which is the only
 * thing the desktop shell actually needs to know before showing the UI.
 */
const LIVENESS_PATH = "/openapi.json";

/**
 * One liveness probe. Resolves false rather than throwing so callers can poll.
 *
 * Any HTTP response counts as live, including an error status: receiving one at
 * all means the socket is accepting and the app is routing. Only a refused
 * connection or a timeout means "not up yet".
 *
 * @param {string} baseUrl e.g. "http://127.0.0.1:8000"
 * @param {number} [timeoutMs]
 * @returns {Promise<boolean>}
 */
async function probeLiveness(baseUrl, timeoutMs = 2_000) {
  try {
    await fetch(`${baseUrl}${LIVENESS_PATH}`, {
      signal: AbortSignal.timeout(timeoutMs),
      // A cached response would make a dead backend look alive.
      cache: "no-store",
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Ask the backend about its own dependencies. Informational only — the desktop
 * app runs fine against a backend with no database, and the UI surfaces
 * per-feature errors far more usefully than a blocking splash screen could.
 *
 * @param {string} baseUrl
 * @param {number} [timeoutMs]
 * @returns {Promise<{ok: boolean, status: number|null, detail: string|null}>}
 */
async function probeDependencies(baseUrl, timeoutMs = 3_000) {
  try {
    const response = await fetch(`${baseUrl}/health`, {
      signal: AbortSignal.timeout(timeoutMs),
      cache: "no-store",
    });
    let detail = null;
    try {
      const body = await response.json();
      detail = body?.message ?? body?.status ?? null;
    } catch {
      // Not JSON; the status code alone is enough.
    }
    return { ok: response.ok, status: response.status, detail };
  } catch (error) {
    return { ok: false, status: null, detail: error.message };
  }
}

const defaultSleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Poll until live, the deadline passes, or `shouldAbort` says the process
 * already died. Dependencies are injected so tests need no real clock.
 *
 * @param {object} options
 * @param {() => Promise<boolean>} options.probe
 * @param {number} [options.timeoutMs]
 * @param {number} [options.intervalMs]
 * @param {(ms: number) => Promise<void>} [options.sleep]
 * @param {() => number} [options.now]
 * @param {() => boolean} [options.shouldAbort] True when waiting is pointless.
 * @returns {Promise<{ok: true} | {ok: false, reason: "timeout"|"exited"}>}
 */
async function waitForLiveness({
  probe,
  timeoutMs = DEFAULT_STARTUP_TIMEOUT_MS,
  intervalMs = DEFAULT_POLL_INTERVAL_MS,
  sleep = defaultSleep,
  now = Date.now,
  shouldAbort = () => false,
}) {
  const deadline = now() + timeoutMs;

  for (;;) {
    if (await probe()) {
      return { ok: true };
    }
    // Checked after the probe so a process that exits just as it becomes
    // live is still reported as a success.
    if (shouldAbort()) {
      return { ok: false, reason: "exited" };
    }
    if (now() >= deadline) {
      return { ok: false, reason: "timeout" };
    }
    await sleep(intervalMs);
  }
}

/**
 * Raised when the backend cannot be started. Carries captured output so the
 * caller can show the user what actually went wrong.
 */
class BackendStartError extends Error {
  constructor(message, { code, logs = "" } = {}) {
    super(message);
    this.name = "BackendStartError";
    this.code = code;
    this.logs = logs;
  }
}

/**
 * Ensure a backend is reachable, adopting or spawning as needed.
 *
 * @param {object} options
 * @param {string} options.repoRoot
 * @param {string} [options.host]
 * @param {number} [options.port]
 * @param {string} options.corsOrigin Origin the renderer will send.
 * @param {(status: string) => void} [options.onStatus]
 * @param {typeof spawn} [options.spawnFn]
 * @param {(p: string) => boolean} [options.fileExists]
 * @param {(baseUrl: string) => Promise<boolean>} [options.probe]
 * @param {number} [options.startupTimeoutMs]
 * @returns {Promise<{mode: "adopted"|"spawned", baseUrl: string, stop: () => Promise<void>}>}
 */
async function startBackend({
  repoRoot,
  host = DEFAULT_HOST,
  port = DEFAULT_PORT,
  corsOrigin,
  onStatus = () => {},
  spawnFn = spawn,
  fileExists = fs.existsSync,
  probe = probeLiveness,
  startupTimeoutMs = DEFAULT_STARTUP_TIMEOUT_MS,
}) {
  const baseUrl = `http://${host}:${port}`;

  onStatus("Looking for a running backend…");
  if (await probe(baseUrl)) {
    onStatus("Connected to the backend already running on this machine.");
    // Not ours to kill.
    return { mode: "adopted", baseUrl, stop: async () => {} };
  }

  const python = resolvePythonPath(repoRoot);
  if (!fileExists(python)) {
    throw new BackendStartError(
      `No Python virtualenv found at ${python}.\n\n` +
        "Set the monorepo up first, from the repository root:\n\n" +
        "  python -m venv .venv\n" +
        "  export PATH=\"$PWD/.venv/bin:$PATH\"\n" +
        "  npm run install:all",
      { code: "NO_VENV" },
    );
  }

  onStatus("Starting the backend…");
  const logs = createLogBuffer();

  const child = spawnFn(
    python,
    [
      "-m",
      "uvicorn",
      "quration.api.server:app",
      "--host",
      host,
      "--port",
      String(port),
    ],
    {
      cwd: repoRoot,
      env: {
        ...process.env,
        // The backend's CORS allowlist covers the Vite dev origins only. This
        // env hook is the supported way to admit the packaged renderer without
        // editing backend source.
        DOGMA_CORS_ORIGINS: [process.env.DOGMA_CORS_ORIGINS, corsOrigin]
          .filter(Boolean)
          .join(","),
        // Unbuffered, so captured logs are useful when startup fails.
        PYTHONUNBUFFERED: "1",
      },
      stdio: ["ignore", "pipe", "pipe"],
    },
  );

  let exit = null;
  child.stdout?.on("data", (chunk) => logs.push(chunk));
  child.stderr?.on("data", (chunk) => logs.push(chunk));
  child.on("exit", (code, signal) => {
    exit = { code, signal };
  });
  child.on("error", (error) => {
    exit = { code: null, signal: null, error };
  });

  const liveness = await waitForLiveness({
    probe: () => probe(baseUrl),
    timeoutMs: startupTimeoutMs,
    shouldAbort: () => exit !== null,
  });

  if (!liveness.ok) {
    await terminate(child);
    const detail =
      liveness.reason === "exited"
        ? `The backend process exited (code ${exit?.code ?? "unknown"}).`
        : `The backend did not start responding within ${Math.round(
            startupTimeoutMs / 1000,
          )}s.`;
    throw new BackendStartError(detail, {
      code: liveness.reason === "exited" ? "EXITED" : "TIMEOUT",
      logs: logs.tail(),
    });
  }

  onStatus("Backend ready.");
  return {
    mode: "spawned",
    baseUrl,
    stop: () => terminate(child),
  };
}

/**
 * SIGTERM, then SIGKILL if the child is still alive after the grace period.
 *
 * @param {import("node:child_process").ChildProcess} child
 * @param {number} [graceMs]
 * @returns {Promise<void>}
 */
function terminate(child, graceMs = SHUTDOWN_GRACE_MS) {
  if (!child || child.exitCode !== null || child.signalCode !== null) {
    return Promise.resolve();
  }

  return new Promise((resolve) => {
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve();
    };

    const timer = setTimeout(() => {
      try {
        child.kill("SIGKILL");
      } catch {
        // Already gone.
      }
      finish();
    }, graceMs);
    // Do not hold the event loop open just to wait out the grace period.
    timer.unref?.();

    child.once("exit", finish);

    try {
      child.kill("SIGTERM");
    } catch {
      finish();
    }
  });
}

module.exports = {
  BackendStartError,
  DEFAULT_HOST,
  DEFAULT_PORT,
  DEFAULT_POLL_INTERVAL_MS,
  DEFAULT_STARTUP_TIMEOUT_MS,
  LIVENESS_PATH,
  SHUTDOWN_GRACE_MS,
  createLogBuffer,
  probeDependencies,
  probeLiveness,
  startBackend,
  terminate,
  waitForLiveness,
};
