"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const {
  buildContentTypesXml,
  buildVsixManifest,
  listPackageFiles,
  shouldPackageFile
} = require("../tools/package-vsix");

const extensionRoot = path.resolve(__dirname, "..");
const packageJson = JSON.parse(fs.readFileSync(path.join(extensionRoot, "package.json"), "utf8"));
const files = listPackageFiles(extensionRoot);
const views = packageJson.contributes.views.dogma;
const editorContextMenus = packageJson.contributes.menus["editor/context"];

assert(files.includes("package.json"));
assert(files.includes("README.md"));
assert(files.includes("media/dogma.svg"));
assert(files.includes("python-service/pyproject.toml"));
assert(files.includes("python-service/biocursor_service/cli.py"));
assert(files.includes("python-service/biocursor_service/repo_paths.py"));
assert(files.includes("python-service/dogma_service/__main__.py"));
assert(!files.some((file) => file.startsWith("python-service/tests/")));
assert(!files.some((file) => file.includes("__pycache__")));
assert(files.includes("src/extension.js"));
assert(files.includes("src/domainValidators.js"));
assert(files.includes("src/localServiceClient.js"));
assert(files.includes("src/serviceProcessManager.js"));
assert(files.includes("src/serviceRunPlan.js"));
assert(files.includes("src/serviceAssistantContext.js"));
assert(files.includes("src/methodGuardrails.js"));
assert(files.includes("src/evidenceLedger.js"));
assert(files.includes("src/edgeEvaluationPlan.js"));
assert(files.includes("src/methodsGraphPreflight.js"));
assert(files.includes("src/methodsGraphSubstrate.js"));
assert(files.includes("src/llmProviderStatus.js"));
assert(files.includes("src/ideReadiness.js"));
assert(files.includes("src/qurationCanvasLink.js"));
assert(files.includes("src/qurationImportClient.js"));
assert(files.includes("src/qurationImportRecord.js"));
assert(files.includes("src/qurationConnectionStatus.js"));
assert(files.includes("src/qurationGraphHistory.js"));
assert(files.includes("src/qurationGraphContext.js"));
assert(files.includes("src/qurationEvents.js"));
assert(files.includes("src/qurationEdgeEvaluationPlan.js"));
assert(files.includes("src/qurationEdgePlan.js"));
assert(files.includes("src/qurationEdgeWorkPackage.js"));
assert(files.includes("src/qurationEdgeSelection.js"));
assert(files.includes("src/qurationEdgePatchHandoff.js"));
assert(files.includes("src/qurationEdgeResolve.js"));
assert(files.includes("src/workflowGraphReport.js"));
assert(files.includes("src/graphWorkbench.js"));
assert(files.includes("src/biologicalGraphWorkbench.js"));
assert(files.includes("src/ideSession.js"));
assert(files.includes("src/nextIdeAction.js"));
assert(files.includes("src/sidecarView.js"));
assert(files.includes("src/agentSuggestion.js"));
assert(files.includes("src/agentHandoff.js"));
assert(files.includes("src/agentWorkbench.js"));
assert(files.includes("src/patchProposals.js"));
assert(files.includes("src/patchDiffPreview.js"));
assert(files.includes("src/patchSelection.js"));
assert(files.includes("src/activePatchSelection.js"));
assert(files.includes("src/statusModel.js"));
assert(files.includes("src/trustPolicy.js"));
assert(!files.some((file) => file.startsWith("test/")));
assert(!files.some((file) => file.startsWith("tools/")));
assert(!files.some((file) => file.endsWith(".vsix")));
assert.strictEqual(shouldPackageFile("src/extension.js"), true);
assert.strictEqual(shouldPackageFile("test/domainValidators.test.js"), false);
assert(views.some((view) => view.id === "dogma.sidecar" && view.type === "webview"));
assert(views.some((view) => view.id === "dogma.inspector" && !view.type));
assert(packageJson.activationEvents.includes("onView:dogma.sidecar"));
assert(packageJson.activationEvents.includes("onCommand:dogma.prepareIdeSession"));
assert(packageJson.activationEvents.includes("onCommand:dogma.runNextIdeAction"));
assert(packageJson.activationEvents.includes("onCommand:dogma.openAgentWorkbench"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateAgentSuggestion"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateAgentHandoff"));
assert(packageJson.activationEvents.includes("onCommand:dogma.reviewActiveFile"));
assert(packageJson.activationEvents.includes("onCommand:dogma.askDogmaAboutSelection"));
assert(packageJson.activationEvents.includes("onCommand:dogma.reviewActiveFinding"));
assert(packageJson.activationEvents.includes("onCommand:dogma.openFinding"));
assert(packageJson.activationEvents.includes("onCommand:dogma.previewActiveFilePatch"));
assert(packageJson.activationEvents.includes("onCommand:dogma.applyActiveFilePatch"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateQurationHandoff"));
assert(packageJson.activationEvents.includes("onCommand:dogma.openQurationGraphUi"));
assert(packageJson.activationEvents.includes("onCommand:dogma.openCurrentQurationGraph"));
assert(packageJson.activationEvents.includes("onCommand:dogma.openQurationCanvasFromWorkspace"));
assert(packageJson.activationEvents.includes("onCommand:dogma.checkQurationStatus"));
assert(packageJson.activationEvents.includes("onCommand:dogma.refreshQurationGraphHistory"));
assert(packageJson.activationEvents.includes("onCommand:dogma.pullQurationGraphContext"));
assert(packageJson.activationEvents.includes("onCommand:dogma.pullQurationGraphEvents"));
assert(packageJson.activationEvents.includes("onCommand:dogma.pullQurationFailedEvents"));
assert(packageJson.activationEvents.includes("onCommand:dogma.selectQurationEdge"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateQurationEdgeEvaluationPlan"));
assert(packageJson.activationEvents.includes("onCommand:dogma.fetchQurationEdgePlan"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateQurationEdgeWorkPackage"));
assert(packageJson.activationEvents.includes("onCommand:dogma.suggestFromQurationEdgeWorkPackage"));
assert(packageJson.activationEvents.includes("onCommand:dogma.previewQurationEdgeSuggestedPatch"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateQurationEdgePatchHandoff"));
assert(packageJson.activationEvents.includes("onCommand:dogma.resolveQurationSelectedEdgeReadout"));
assert(packageJson.activationEvents.includes("onCommand:dogma.applyQurationEdgeSuggestedPatch"));
assert(packageJson.activationEvents.includes("onCommand:dogma.checkIdeReadiness"));
assert(packageJson.activationEvents.includes("onCommand:dogma.importWorkspaceToQuration"));
assert(packageJson.activationEvents.includes("onCommand:dogma.openLastQurationImport"));
assert(packageJson.activationEvents.includes("onCommand:dogma.generateMethodsGraphPreflight"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openAgentWorkbench"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateAgentSuggestion"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateAgentHandoff"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.runNextIdeAction" && command.title === "Dogma: Run Next IDE Action"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openGraphWorkbench" && command.title === "Dogma: Open Local Workflow Guardrails"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openBiologicalGraphWorkbench" && command.title === "Dogma: Open Local Biological Edge Guardrails"));
assert(!packageJson.contributes.commands.some((command) => command.title === "Dogma: Open Graph Workbench"));
assert(!packageJson.contributes.commands.some((command) => command.title === "Dogma: Open Biological Graph"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.reviewActiveFile"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.askDogmaAboutSelection"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.reviewActiveFinding"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openFinding"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.previewActiveFilePatch"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.applyActiveFilePatch"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateQurationHandoff"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openQurationGraphUi"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openCurrentQurationGraph" && command.title === "Dogma: Open Current quration Graph"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openQurationCanvasFromWorkspace"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.checkQurationStatus"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.refreshQurationGraphHistory"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.pullQurationGraphContext"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.pullQurationGraphEvents"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.pullQurationFailedEvents"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.selectQurationEdge"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateQurationEdgeEvaluationPlan"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.fetchQurationEdgePlan"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateQurationEdgeWorkPackage"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.suggestFromQurationEdgeWorkPackage"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.previewQurationEdgeSuggestedPatch"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateQurationEdgePatchHandoff"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.resolveQurationSelectedEdgeReadout"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.applyQurationEdgeSuggestedPatch"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.checkIdeReadiness"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.importWorkspaceToQuration"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.openLastQurationImport"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.generateMethodsGraphPreflight"));
assert(packageJson.contributes.commands.some((command) => command.command === "dogma.prepareIdeSession"));
assert.strictEqual(packageJson.contributes.configuration.properties["dogma.serviceMode"].default, "auto");
assert.strictEqual(packageJson.contributes.configuration.properties["dogma.serviceCwd"].default, "auto");
assert.strictEqual(packageJson.contributes.configuration.properties["dogma.qurationApiUrl"].default, "http://localhost:8000");
assert.strictEqual(packageJson.contributes.configuration.properties["dogma.qurationTimeoutMs"].default, 5000);
assert(editorContextMenus.some((item) => item.command === "dogma.askDogmaAboutSelection" && item.group === "dogma@1"));
assert(editorContextMenus.some((item) => item.command === "dogma.reviewActiveFinding" && item.group === "dogma@2"));
assert(editorContextMenus.some((item) => item.command === "dogma.reviewActiveFile" && item.group === "dogma@3"));
assert(editorContextMenus.some((item) => item.command === "dogma.previewActiveBioFile" && item.group === "dogma@4"));
assert(editorContextMenus.some((item) => item.command === "dogma.previewActiveFilePatch" && item.group === "dogma@5"));
assert(editorContextMenus.some((item) => item.command === "dogma.applyActiveFilePatch" && item.group === "dogma@6"));
assert(editorContextMenus.every((item) => item.when.includes("editorTextFocus") && item.when.includes("resourceScheme == file")));

const manifest = buildVsixManifest(packageJson);
assert(manifest.includes('Id="dogma"'));
assert(manifest.includes('Version="0.2.53"'));
assert(manifest.includes('Publisher="manu-tej"'));
assert(manifest.includes("extension/package.json"));
assert(manifest.includes("extension/README.md"));
assert(manifest.includes("dogma,bioinformatics,genomics,workflow,nextflow,vscode,cursor"));

const contentTypes = buildContentTypesXml();
assert(contentTypes.includes('Extension="json"'));
assert(contentTypes.includes('Extension="js"'));
assert(contentTypes.includes('Extension="py"'));
assert(contentTypes.includes('Extension="svg"'));
assert(contentTypes.includes('Extension="toml"'));
assert(contentTypes.includes('Extension="vsixmanifest"'));

console.log("VSIX package tests passed");
